[package]
name = "rpi"
version = "0.1.0"
edition = "2021"

[dependencies]
futures-util = "0.3.30"
rppal = "0.18.0"
serde = "1.0.203"
serde_json = "1.0.117"
tokio = {version="1.38.0", features = ["full"] }
tokio-serial = "5.4.4"
tokio-tungstenite = "0.23.1"
